### PR TITLE
#563 Added alternative implementation with WatcherService wrapper

### LINKED ISSUE #563: ffm PWM  channel other than 0 fail to export after reboot.
There are two statements that use chip rather than channel in PwmFFMHardware     

Reboot and repeated attempt to create a PWM on a channel > 0 will then work after two fails.  Happens as the first attempts each progress further through the initialization code.     

I will continue investigation of Smoke test fail along with these fixes.

### PR DESCRIPTION
**Pull request by DigitalSmile**
Basic implementation of NIO2 wrapper for file creation waiting with fixed timeout.

### CODE REVIEW

File: plugins/pi4j-plugin-ffm/src/main/java/com/pi4j/plugin/ffm/common/FileWatcher.java [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import java.nio.file.*;
+import java.time.Duration;
+import java.time.Instant;
+
+/**
+ * File watcher wrapper to wait for file is ready with defined timeout.
+ */
+public class FileWatcher implements AutoCloseable {
+    // in ms
+    private static final int TIMEOUT = 100;
```
Comment (eitch) [inline plugins/pi4j-plugin-ffm/src/main/java/com/pi4j/plugin/ffm/common/FileWatcher.java]: Why not rename TIMEOUT_MS?

Comment (eitch) [reply plugins/pi4j-plugin-ffm/src/main/java/com/pi4j/plugin/ffm/common/FileWatcher.java]: And possibly pass the timeout on construction?

**Review by eitch — APPROVED** [review]

**Comment by taartspi** [comment]
code looks good.     I tried the PR that is merged, removes my direct delay and uses the existing waitForFile   This does not work.  The testcase creates the PWM and immediately call ON.  The On cannot access the file  open of the period,  fails access   Maybe the waitForFile File.access returns OK (0) before the file is fully created.  I will try this code next.

**Review by taartspi — COMMENTED** [review]
code looks good. I tried the PR that is merged, removes my direct delay and uses the existing waitForFile This does not work. The testcase creates the PWM and immediately call ON. The On cannot access the file open of the period, fails access Maybe the waitForFile File.access returns OK (0) before the file is fully created. I will try this code next.

**Comment by taartspi** [comment]
After reboot no pwm2 directory exists
  Fails first use in the smoketest   

[main] INFO com.pi4j.test.Main - Test PWM (freq: 1, dc: 50)
FAILED
Test failure: Error during call to method 'open' with data '[/sys/class/pwm/pwmchip0/pwm2/period, 1]': Permission denied (13)
The pwm2 directory was created  
Next run of the test worked correctly
